baseURL = "http://socialists.space/"
languageCode = "en-us"
title = "Space Coast DSA"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Register Interest"
    url = "/register-interest"
    weight = 2

[[menu.main]]
    name = "Facebook"
    url = "http://facebook.com/socialists.space"
    weight = 3

[[menu.main]]
    name = "Twitter"
    url = "http://twitter.com/spacecoastdsa"
    weight = 4
